name: Deploy Worker

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      APP_VERSION: ${{ github.ref_type == 'tag' && github.ref_name || 'vdev' }}
      REPOSITORY_URL: ${{ format('{0}/{1}', github.server_url, github.repository) }}
      WORKER_NAME: ${{ vars.CLOUDFLARE_WORKER_NAME || 'note' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Set app version
        run: |
          APP_VERSION_ESCAPED=${APP_VERSION//\'/\\\'}
          REPOSITORY_URL_ESCAPED=${REPOSITORY_URL//\'/\\\'}
          cat > src/version.ts <<EOF
          export const APP_VERSION = '${APP_VERSION_ESCAPED}';
          export const REPOSITORY_URL = '${REPOSITORY_URL_ESCAPED}';
          EOF

      - name: Verify app
        run: npm run verify

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy --name ${{ env.WORKER_NAME }}
